class IntentRouter:
    """
    Routes interpreted intents to the appropriate module.

    The IntentRouter receives structured intents from the interpreter
    and determines which module should handle the request. If no module
    is capable of handling the intent, the request falls back to the LLM.
    """

    def __init__(self, context):
        """
        Initialize the intent router.

        Args:
            context (RuntimeContext)
        """

        self.context = context
        self.logger = context.logger.getChild("Router") if context.logger else None

        if self.logger:
            self.logger.info("Initialized.")

    # --------------------------------------------------
    # Routing
    # --------------------------------------------------

    def route(self, intent):
        """
        Route an intent to the correct module.

        Args:
            intent (Intent)

        Returns:
            str:
                Response generated by the handling module or LLM.
        """

        intent_name = intent.name

        if self.logger:
            self.logger.debug(f"Routing intent: {intent_name}")

        # Search registered modules
        for module in self.context.modules.values():

            if hasattr(module, "canHandle") and module.canHandle(intent):

                if self.logger:
                    self.logger.debug(f"Intent '{intent_name}' handled by {module.__class__.__name__}")

                return module.handle(intent)

        # --------------------------------------------------
        # Fallback to LLM
        # --------------------------------------------------

        if self.logger:
            self.logger.debug(f"No module handled intent '{intent_name}', using LLM fallback")

        llm = self.context.require("llm")

        return llm.generateResponse(intent.raw)
