llm:
  model: llama3.1:8b
  endpoint: http://localhost:11434/api/generate

  history:
    enabled: true
    limit: 25

  memory:
    enabled: true

database:
  host: localhost
  port: 3306
  name: aura
  user: change_me
  password: change_me

threading:
  max_threads: 10
