"""Shared helpers for Aura email tests."""

from __future__ import annotations

from pathlib import Path
from types import SimpleNamespace
import shutil
import tempfile

from testing.tests.support.fakes import make_context


class FakeEventBus:
    """Record email events without the full runtime event stack."""

    def __init__(self):
        self.events = []
        self.subscriptions = {}

    def emit(self, name, data=None):
        payload = {"name": name, "data": dict(data or {})}
        self.events.append(payload)
        for callback in self.subscriptions.get(name, []):
            callback(payload)
        return payload

    def subscribe(self, name, handler):
        self.subscriptions.setdefault(name, []).append(handler)

    def unsubscribe(self, name, handler):
        handlers = self.subscriptions.get(name, [])
        if handler in handlers:
            handlers.remove(handler)


class FakeNotificationManager:
    """Capture notifications generated by the email module."""

    def __init__(self):
        self.created = []

    def createNotification(self, payload, eventName=""):
        record = {"payload": dict(payload), "eventName": eventName}
        self.created.append(record)
        return record


class FakeScheduleManager:
    """Capture schedule items created for scheduled emails."""

    def __init__(self):
        self.created = []

    def createScheduleItem(self, **fields):
        self.created.append(dict(fields))
        return {"itemId": f"schedule-{len(self.created)}", **fields}


def build_email_context(email_config=None):
    """Create a runtime context configured for email tests."""

    tempdir_path = Path(tempfile.mkdtemp())
    context = make_context(extra={})
    context.config._data.setdefault("email", {})
    context.config._data["email"].update(
        {
            "emailEnabled": True,
            "emailMonitoringEnabled": True,
            "emailSyncIntervalSeconds": 60,
            "emailNotificationsEnabled": True,
            "emailDefaultAccount": None,
            "emailCacheEnabled": True,
            "emailRequireConfirmationToSend": True,
            "emailRequireConfirmationToDelete": True,
            "databasePath": str(tempdir_path / "email.sqlite3"),
        }
    )
    if email_config:
        context.config._data["email"].update(email_config)
    context.eventManager = FakeEventBus()
    context.notificationManager = FakeNotificationManager()
    context.personalSchedule = FakeScheduleManager()
    context._emailTempdir = SimpleNamespace(
        name=str(tempdir_path),
        cleanup=lambda: shutil.rmtree(tempdir_path, ignore_errors=True),
    )
    return context
