"""Core implementation for `inputManager` in the Aura assistant project."""

class InputManager:
    """
    Handles incoming user input for Aura.

    The InputManager is responsible for:
    - Receiving raw user input
    - Detecting command inputs ("/" prefix)
    - Routing commands to the CommandHandler
    - Routing normal input through the interpreter and intent system

    This class does NOT handle:
    - Memory logic
    - Business logic
    - LLM calls directly
    """

    def __init__(self, context):
        """
        Initialize the InputManager.

        Args:
            context (RuntimeContext):
                Global runtime context.
        """

        self.context = context
        # Logger
        self.logger = None
        if context.logger:
            self.logger = context.logger.getChild("Input")
        if self.logger:
            self.logger.info("Initialized.")


    # --------------------------------------------------
    # Input Processing
    # --------------------------------------------------
    def process(self, text: str) -> str:
        """
        Process incoming user input.

        Args:
            text (str):
                Raw user input.

        Returns:
            str:
                Response generated by the system.
        """

        if self.logger:
            self.logger.debug(f"Received input: {text}")


        # --------------------------------
        # Command Handling
        # --------------------------------
        if text.strip().startswith("/"):
            commandHandler = self.context.require("commandHandler")
            if self.logger:
                self.logger.debug("Routing to CommandHandler")
            return commandHandler.handle(text)


        # --------------------------------
        # Normal Input Flow
        # --------------------------------
        interpreter = self.context.require("interpreter")
        router = self.context.require("intentRouter")
        # Convert text → intent
        intent = interpreter.interpret(text)
        # Route intent → module/LLM
        response = router.route(intent)
        return response
